variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

stages:
    - build
    - test
    - package
    


cache:
  paths:
    - .m2/repository
    - target

build_job:
  stage: build
  tags:
    - ssh

  script: 
    - echo "Maven compile started"
    - "mvn compile"


test_job:
  stage: test
  tags:
    - ssh 

  script: 
    - echo "Maven test started"
    - "mvn clean test"

package_job:
  stage: package
  tags:
    - ssh 

  script: 
    - echo "Maven packaging started"
    - "mvn package"

#hi 
